config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries, param: :permalink, path: ''

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  has_many :translations, inverse_of: :dictionary

  accepts_nested_attributes_for :translations

  validates :title, presence: true
  validates :permalink, presence: true, uniqueness: true

  before_validation :generate_permalink, on: :create

  def to_param
    permalink
  end

  private

  def generate_permalink
    self.permalink = loop do
      random_token = [0..9, 'a'..'z', 'A'..'Z'].map(&:to_a).flatten.sample(11).join
      break random_token unless self.class.exists?(permalink: random_token)
    end
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :dictionary, inverse_of: :translations

  validates :dictionary, presence: true
  validates :source, presence: true
  validates :destination, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
    @dictionary.translations.build
  end

  # GET /dictionaries/1/edit
  def edit
    @dictionary.translations.build
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dictionary
    @dictionary = Dictionary.find_by!(permalink: params[:permalink])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dictionary_params
    params.require(:dictionary).permit(
      :title,
      translations_attributes: [:id, :source, :destination, :_destroy]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.slim
= form_for @dictionary do |f|
  - if @dictionary.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dictionary.errors.count, "error")} prohibited this dictionary from being saved:"
      ul
        - @dictionary.errors.full_messages.each do |message|
          li = message

  = f.text_field :title, placeholder: @dictionary.class.human_attribute_name(:title)

  ul
    = f.fields_for :translations do |ff|
      li
        = ff.text_field :source, placeholder: @dictionary.class.human_attribute_name(:source)
        span<>
          | =>
        = ff.text_field :destination, placeholder: @dictionary.class.human_attribute_name(:destination)

  .actions = f.submit

app/views/dictionaries/edit.slim
h1 Editing dictionary

== render 'form'

= link_to 'Show', @dictionary
'|
= link_to 'Back', dictionaries_path

app/views/dictionaries/index.slim
h1 Listing dictionaries

table
  thead
    tr
      th
        = @dictionaries.klass.human_attribute_name(:title)
      th
        = @dictionaries.klass.human_attribute_name(:permalink)
      th

  tbody
    - @dictionaries.each do |dictionary|
      tr
        td
          = dictionary.title
        td
          = dictionary.permalink
        td
          span> = link_to 'Show', dictionary
          span> = link_to 'Edit', edit_dictionary_path(dictionary)
          span> = link_to 'Destroy', dictionary, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Dictionary', new_dictionary_path

app/views/dictionaries/new.slim
h1 New dictionary

== render 'form'

= link_to 'Back', dictionaries_path

app/views/dictionaries/show.slim
p#notice = notice

h1
  = @dictionary.title

ul
  - @dictionary.translations.each do |translation|
    li
      = translation.source
      span<>
        | =>
      = translation.destination

#honyaku
  iframe width="100%" height="800px"

  = javascript_include_tag 'https://rawgit.com/padolsey/jquery.fn/master/cross-domain-ajax/jquery.xdomainajax.js'

  javascript:
    translations = #{raw @dictionary.translations.map { |t| [t.source, t.destination] }};
    target_url = '#{params[:url]}';

  coffee:
    $(document).ready(->
      $.get(target_url, (data) ->
        text = data.responseText
        $(translations).each(->
          source = new RegExp(this[0], 'g')
          destination = this[1]
          text = text.replace(source, destination)
        )
        iframe = $('#honyaku > iframe')[0]
        doc = iframe.document || iframe.contentDocument || iframe.contentWindow.document
        doc.open()
        doc.writeln('<base href="' + url_base(target_url) + '">' + text)
        doc.close()
      )
    )

    url_base = (url) ->
      element = document.createElement('a')
      element.href = url
      element.protocol + '//' + element.host

= link_to 'Edit', edit_dictionary_path(@dictionary)
'|
= link_to 'Back', dictionaries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HonyakuMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>